# use the latest ubuntu environment (20.04) available on travis
dist: focal

language: go

go:
  - 1.17.x

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install clang llvm libelf-dev gcc-multilib libpcap-dev
  - sudo apt-get -y install linux-tools-$(uname -r)
  - sudo apt-get -y install elfutils dwarves git libbsd-dev bridge-utils
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
  - docker pull loxilbio/loxilb:beta
  - docker run -u root --cap-add SYS_ADMIN   --restart unless-stopped --privileged -dit -v /dev/log:/dev/log --entrypoint /root/loxilb-io/loxilb/loxilb --name loxilb loxilbio/loxilb:beta


install:
  - wget https://github.com/loxilb-io/iproute2/archive/refs/heads/main.zip
  - unzip main.zip
  - pushd iproute2-main/libbpf/src/ && mkdir build && DESTDIR=build make install && popd
  - pushd iproute2-main/ &&  export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:`pwd`/libbpf/src/ && LIBBPF_FORCE=on LIBBPF_DIR=`pwd`/libbpf/src/build ./configure && make && sudo cp -f tc/tc /usr/local/sbin/ntc && popd
  - pushd iproute2-main/libbpf/src/ && sudo make install && popd

script:
  - sudo mkdir -p /opt/loxilb
  - ebpf/utils/mkllb_bpffs.sh 
  - make
  - sudo -E env "PATH=$PATH" make test
  - ebpf/utils/mkenv.sh docker
  - ebpf/utils/basic-sanity-ci.sh

