name: Build-Check-CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      userInput:
        description: 'Enter string to print at end'
        required: true
        default: 'Finished'
      tags:
        description: 'Build Check'  

jobs:

  build:
    name: build-check-ci

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install Latest Docker
      run: |
        # for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do sudo apt-get remove $pkg; done
        # sudo apt-get update
        # sudo apt-get install ca-certificates curl gnupg
        # sudo install -m 0755 -d /etc/apt/keyrings
        # curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        # sudo chmod a+r /etc/apt/keyrings/docker.gpg

        # echo \
        #  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        #  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
        # sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        # sudo apt-get update
        # sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        echo "Done"

    - name: Build the loxilb Docker image
      run: |
        docker build . --tag ghcr.io/loxilb-io/loxilb:latest
        docker run -u root --cap-add SYS_ADMIN  --restart unless-stopped --privileged -dit -v /dev/log:/dev/log --name loxilb ghcr.io/loxilb-io/loxilb:latest
    - run: echo ${{ github.event.inputs.userInput }}
